//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCRestApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calisanlar
    {
        public int CalisanId { get; set; }
        public string AdSoyad { get; set; }
        public string Pozisyon { get; set; }
        public Nullable<int> Yas { get; set; }
        public Nullable<int> Maas { get; set; }
    }
}
